# Generated by Django 5.0.3 on 2024-03-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_category_contacts_remove_myuser_color_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Subtasks',
            new_name='Subtask',
        ),
    ]
