# Generated by Django 5.0.3 on 2024-03-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_rename_contacts_contact_rename_subtasks_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_users',
            field=models.ManyToManyField(default=None, null=True, to='kanban.contact'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(default='Low', max_length=25),
        ),
    ]
