# Generated by Django 5.0.3 on 2024-03-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_alter_task_assigned_users_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_users',
            field=models.ManyToManyField(to='kanban.contact'),
        ),
    ]
