# Generated by Django 5.0.3 on 2024-03-25 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0008_alter_task_assigned_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='subtask',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='kanban.subtask'),
        ),
    ]
