# Generated by Django 5.0.3 on 2024-03-26 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0012_alter_task_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_users',
            new_name='assignedTo',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtask',
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='kanban.task'),
            preserve_default=False,
        ),
    ]
